-- 코드를 작성해주세요
SELECT COUNT(fi.FISH_TYPE) as 'FISH_COUNT', fni.FISH_NAME
FROM FISH_INFO as fi
INNER JOIN FISH_NAME_INFO as fni
ON fi.FISH_TYPE = fni.FISH_TYPE
GROUP BY fi.FISH_TYPE, fni.FISH_NAME
ORDER BY FISH_COUNT DESC;
